language: python
python:
  - "2.7"
env: DJANGO_SETTINGS_MODULE=perma.settings.settings_test CFLAGS="-O0"

before_install: cd perma_web
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  coverage run --source='.' --omit='lib/*,perma/migrations/*' manage.py test perma
after_success:
  - coveralls debug
  - coveralls