language: python
python:
  - "2.7"
env: CFLAGS="-O0"

# make sure perma.dev resolves to localhost so our tests work
addons:
  hosts:
    - perma.dev

cache:
  directories:
    - $HOME/.cache/pip

before_install:
  - cp services/travis/settings.py perma_web/perma/settings/
  - cd perma_web
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - mysql -e 'CREATE DATABASE perma;'

  # try to avoid mysql has gone away errors
  - mysql -e 'SET GLOBAL max_allowed_packet = 64*1024*1024;'
  - mysql -e 'SET GLOBAL wait_timeout = 36000;'

  - python manage.py collectstatic --noinput
script:
  fab test
after_success:
  - coveralls

# See: http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade#tl%3Bdr
sudo: false

deploy:
  provider: heroku
  strategy: git
  api_key:
    deploy-develop-to-heroku-on-successful-travis-ci-build:
      secure: X44fGPD+xQCeKFr3smBXOwWeXtkTNlzIWkJbA4sEP3fPVZvso8EDgG3SuQ4G7CF9kgM/pquFp+00/AiE2fPL644iVNJXFW/5ajxpMCc7pFEU8Fbba2uJAA51W+sK/n9hKMxc0ZCk0JA7TZ6sX7cOElMScFnea2ZeuW+XtanD3hM=
  app:
    deploy-develop-to-heroku-on-successful-travis-ci-build: perma-staging
  on:
    repo: leppert/perma