language: python
python:
  - "2.7"
env: CFLAGS="-O0"

# make sure perma.dev resolves to localhost so our tests work
addons:
  hosts:
    - perma.dev

before_install:
  - cp services/travis/settings.py perma_web/perma/settings/
  - cd perma_web
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - mysql -e 'create database perma;'

  # try to avoid mysql has gone away errors
  # via https://github.com/travis-ci/travis-ci/issues/2250
  - echo -e "[server]\nmax_allowed_packet=64M\nwait_timeout=36000" | sudo tee -a /etc/mysql/conf.d/perma.cnf
  - sudo service mysql restart
  - mysql -e "SHOW VARIABLES LIKE 'max_allowed_packet';"
  - mysql -e "SHOW VARIABLES LIKE 'wait_timeout';"
  - mysql -e "SET GLOBAL wait_timeout = 36000;"
  - mysql -e "SET GLOBAL max_allowed_packet = 67108864;"
  - mysql -e "SHOW VARIABLES LIKE 'max_allowed_packet';"
  - mysql -e "SHOW VARIABLES LIKE 'wait_timeout';"

  - python manage.py collectstatic --noinput
script:
  fab test
after_success:
  - coveralls