language: python
python:
  - "2.7"
env: CFLAGS="-O0"

before_install:
  - cp services/travis/settings.py perma_web/perma/settings/
  - cd perma_web
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - mysql -e 'create database perma;'
  - python manage.py collectstatic --noinput
script:
  fab test
after_success:
  - coveralls debug
  - coveralls